# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GayaEmp',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login', blank=True)),
                ('emp_email', models.EmailField(unique=True, max_length=255, verbose_name=b'email address')),
                ('emp_name', models.CharField(max_length=128)),
                ('emp_rank', models.CharField(max_length=128)),
                ('emp_phone', models.CharField(max_length=128)),
                ('emp_address', models.CharField(max_length=255)),
                ('emp_job', models.CharField(max_length=255)),
                ('emp_pwon', models.IntegerField(default=0, null=True, blank=True)),
                ('emp_created', models.DateTimeField(auto_now_add=True)),
                ('emp_modified', models.DateTimeField(auto_now=True)),
                ('emp_note', models.TextField(null=True, blank=True)),
                ('emp_comments', models.PositiveSmallIntegerField(default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssembleReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asr_psn', models.CharField(max_length=128)),
                ('asr_pro', models.CharField(max_length=128)),
                ('asr_startday', models.DateField()),
                ('asr_start', models.IntegerField(default=0, null=True, blank=True)),
                ('asr_completeday', models.DateField(null=True, blank=True)),
                ('asr_c_emp', models.CharField(max_length=128, null=True, blank=True)),
                ('asr_complete', models.IntegerField(default=0, null=True, blank=True)),
                ('asr_add', models.IntegerField(default=0, null=True, blank=True)),
                ('asr_report', models.FileField(null=True, upload_to=b'asr/file/%Y/%m/%d', blank=True)),
                ('asr_out', models.IntegerField(default=0, null=True, blank=True)),
                ('asr_author', models.CharField(max_length=128)),
                ('asr_created', models.DateTimeField(auto_now_add=True)),
                ('asr_modified', models.DateTimeField(auto_now=True)),
                ('asr_note', models.TextField(null=True, blank=True)),
                ('asr_s_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('dlr_when', models.DateField()),
                ('dlr_where', models.CharField(max_length=128)),
                ('dlr_how', models.CharField(max_length=128)),
                ('dlr_complete', models.IntegerField(default=0, null=True, blank=True)),
                ('dlr_add', models.IntegerField(default=0, null=True, blank=True)),
                ('dlr_author', models.CharField(max_length=128)),
                ('dlr_created', models.DateTimeField(auto_now_add=True)),
                ('dlr_modified', models.DateTimeField(auto_now=True)),
                ('dlr_note', models.TextField(null=True, blank=True)),
                ('dlr_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gaya_HA201TP_Comments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaCusComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaCustomer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cus_name', models.CharField(max_length=128)),
                ('cus_section', models.CharField(max_length=128)),
                ('cus_rsps', models.CharField(max_length=128)),
                ('cus_rank', models.CharField(max_length=128)),
                ('cus_department', models.CharField(max_length=128)),
                ('cus_phone', models.CharField(max_length=128)),
                ('cus_rphone', models.CharField(max_length=128)),
                ('cus_email', models.CharField(max_length=128)),
                ('cus_address', models.CharField(max_length=255)),
                ('cus_author', models.CharField(max_length=128)),
                ('cus_created', models.DateTimeField(auto_now_add=True)),
                ('cus_modified', models.DateTimeField(auto_now=True)),
                ('cus_note', models.TextField(null=True, blank=True)),
                ('cus_comments', models.PositiveSmallIntegerField(default=0, null=True)),
                ('cus_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GayaEmpComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GayaMaterialInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('mtr_class', models.CharField(max_length=128)),
                ('mtr_name', models.CharField(max_length=128)),
                ('mtr_desc', models.TextField(null=True)),
                ('mtr_total', models.IntegerField()),
                ('mtr_maker', models.CharField(max_length=128)),
                ('mtr_purchase', models.CharField(max_length=128)),
                ('mtr_purchaseday', models.DateField()),
                ('mtr_repository', models.CharField(max_length=128)),
                ('mtr_finished_sn', models.IntegerField(default=0, null=True, blank=True)),
                ('mtr_author', models.CharField(max_length=128)),
                ('mtr_created', models.DateTimeField(auto_now_add=True)),
                ('mtr_modified', models.DateTimeField(auto_now=True)),
                ('mtr_note', models.TextField(null=True, blank=True)),
                ('mtr_comments', models.PositiveSmallIntegerField(default=0, null=True)),
                ('mtr_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GayaMaterialSN',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('msn_class', models.CharField(max_length=128)),
                ('msn_pn', models.CharField(max_length=128)),
                ('msn_sn', models.CharField(unique=True, max_length=128)),
                ('msn_pro', models.CharField(max_length=128, null=True, blank=True)),
                ('msn_psn', models.CharField(max_length=128, null=True, blank=True)),
                ('msn_state', models.IntegerField(default=0, null=True, blank=True)),
                ('msn_pson', models.IntegerField(default=0, null=True, blank=True)),
                ('msn_using', models.IntegerField(default=0, null=True, blank=True)),
                ('msn_out', models.IntegerField(default=0, null=True, blank=True)),
                ('msn_author', models.CharField(max_length=128)),
                ('msn_created', models.DateTimeField(auto_now_add=True)),
                ('msn_modified', models.DateTimeField(auto_now=True)),
                ('msn_note', models.TextField(null=True, blank=True)),
                ('msn_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('msn_mtr', models.ForeignKey(to='erp.GayaMaterialInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GayaMtrComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_mtr', models.ForeignKey(to='erp.GayaMaterialInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GayaOrdComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaOrder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ord_title', models.CharField(max_length=255)),
                ('ord_ponum', models.CharField(max_length=128)),
                ('ord_total', models.IntegerField()),
                ('ord_os', models.CharField(max_length=128, null=True, blank=True)),
                ('ord_orderday', models.DateField()),
                ('ord_delivery', models.DateField()),
                ('ord_warranty', models.DateField()),
                ('ord_complete', models.IntegerField(default=0, null=True)),
                ('ord_author', models.CharField(max_length=128)),
                ('ord_created', models.DateTimeField(auto_now_add=True)),
                ('ord_modified', models.DateTimeField(auto_now=True)),
                ('ord_note', models.TextField(null=True, blank=True)),
                ('ord_comments', models.PositiveSmallIntegerField(default=0, null=True)),
                ('ord_cus', models.ForeignKey(to='erp.GayaCustomer')),
                ('ord_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GayaProductInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pro_class', models.CharField(max_length=128)),
                ('pro_name', models.CharField(max_length=255)),
                ('pro_info', models.TextField()),
                ('pro_author', models.CharField(max_length=128)),
                ('pro_created', models.DateTimeField(auto_now_add=True)),
                ('pro_note', models.TextField(null=True, blank=True)),
                ('pro_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSccComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaScfComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSclCommon',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('scc_title', models.CharField(max_length=255)),
                ('scc_name', models.CharField(max_length=128)),
                ('scc_pw', models.CharField(max_length=128)),
                ('scc_contents', models.TextField()),
                ('scc_author', models.CharField(max_length=128)),
                ('scc_created', models.DateTimeField(auto_now_add=True)),
                ('scc_modified', models.DateTimeField(auto_now=True)),
                ('scc_file01', models.FileField(null=True, upload_to=b'scc/file/%Y/%m/%d', blank=True)),
                ('scc_file02', models.FileField(null=True, upload_to=b'scc/file/%Y/%m/%d', blank=True)),
                ('scc_file03', models.FileField(null=True, upload_to=b'scc/file/%Y/%m/%d', blank=True)),
                ('scc_img01', models.ImageField(null=True, upload_to=b'scc/img/%Y/%m/%d', blank=True)),
                ('scc_img02', models.ImageField(null=True, upload_to=b'scc/img/%Y/%m/%d', blank=True)),
                ('scc_img03', models.ImageField(null=True, upload_to=b'scc/img/%Y/%m/%d', blank=True)),
                ('scc_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSclFree',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('scf_title', models.CharField(max_length=255)),
                ('scf_name', models.CharField(max_length=128)),
                ('scf_pw', models.CharField(max_length=128)),
                ('scf_contents', models.TextField()),
                ('scf_author', models.CharField(max_length=128)),
                ('scf_created', models.DateTimeField(auto_now_add=True)),
                ('scf_modified', models.DateTimeField(auto_now=True)),
                ('scf_file01', models.FileField(null=True, upload_to=b'scf/file/%Y/%m/%d', blank=True)),
                ('scf_file02', models.FileField(null=True, upload_to=b'scf/file/%Y/%m/%d', blank=True)),
                ('scf_file03', models.FileField(null=True, upload_to=b'scf/file/%Y/%m/%d', blank=True)),
                ('scf_img01', models.ImageField(null=True, upload_to=b'scf/img/%Y/%m/%d', blank=True)),
                ('scf_img02', models.ImageField(null=True, upload_to=b'scf/img/%Y/%m/%d', blank=True)),
                ('scf_img03', models.ImageField(null=True, upload_to=b'scf/img/%Y/%m/%d', blank=True)),
                ('scf_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSclQanda',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('scq_title', models.CharField(max_length=255)),
                ('scq_name', models.CharField(max_length=128)),
                ('scq_pw', models.CharField(max_length=128)),
                ('scq_contents', models.TextField()),
                ('scq_author', models.CharField(max_length=128)),
                ('scq_created', models.DateTimeField(auto_now_add=True)),
                ('scq_modified', models.DateTimeField(auto_now=True)),
                ('scq_file01', models.FileField(null=True, upload_to=b'scq/file/%Y/%m/%d', blank=True)),
                ('scq_file02', models.FileField(null=True, upload_to=b'scq/file/%Y/%m/%d', blank=True)),
                ('scq_file03', models.FileField(null=True, upload_to=b'scq/file/%Y/%m/%d', blank=True)),
                ('scq_img01', models.ImageField(null=True, upload_to=b'scq/img/%Y/%m/%d', blank=True)),
                ('scq_img02', models.ImageField(null=True, upload_to=b'scq/img/%Y/%m/%d', blank=True)),
                ('scq_img03', models.ImageField(null=True, upload_to=b'scq/img/%Y/%m/%d', blank=True)),
                ('scq_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSclRecommend',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('scr_title', models.CharField(max_length=255)),
                ('scr_name', models.CharField(max_length=128)),
                ('scr_pw', models.CharField(max_length=128)),
                ('scr_contents', models.TextField()),
                ('scr_author', models.CharField(max_length=128)),
                ('scr_created', models.DateTimeField(auto_now_add=True)),
                ('scr_modified', models.DateTimeField(auto_now=True)),
                ('scr_file01', models.FileField(null=True, upload_to=b'scr/file/%Y/%m/%d', blank=True)),
                ('scr_file02', models.FileField(null=True, upload_to=b'scr/file/%Y/%m/%d', blank=True)),
                ('scr_file03', models.FileField(null=True, upload_to=b'scr/file/%Y/%m/%d', blank=True)),
                ('scr_img01', models.ImageField(null=True, upload_to=b'scr/img/%Y/%m/%d', blank=True)),
                ('scr_img02', models.ImageField(null=True, upload_to=b'scr/img/%Y/%m/%d', blank=True)),
                ('scr_img03', models.ImageField(null=True, upload_to=b'scr/img/%Y/%m/%d', blank=True)),
                ('scr_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaScqComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_scq', models.ForeignKey(to='erp.GayaSclQanda')),
            ],
        ),
        migrations.CreateModel(
            name='GayaScrComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_scr', models.ForeignKey(to='erp.GayaSclRecommend')),
            ],
        ),
        migrations.CreateModel(
            name='GayaSptDev',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('std_title', models.CharField(max_length=255)),
                ('std_name', models.CharField(max_length=128)),
                ('std_pw', models.CharField(max_length=128)),
                ('std_contents', models.TextField()),
                ('std_author', models.CharField(max_length=128)),
                ('std_created', models.DateTimeField(auto_now_add=True)),
                ('std_modified', models.DateTimeField(auto_now=True)),
                ('std_file01', models.FileField(null=True, upload_to=b'std/file/%Y/%m/%d', blank=True)),
                ('std_file02', models.FileField(null=True, upload_to=b'std/file/%Y/%m/%d', blank=True)),
                ('std_file03', models.FileField(null=True, upload_to=b'std/file/%Y/%m/%d', blank=True)),
                ('std_file04', models.FileField(null=True, upload_to=b'std/file/%Y/%m/%d', blank=True)),
                ('std_file05', models.FileField(null=True, upload_to=b'std/file/%Y/%m/%d', blank=True)),
                ('std_img01', models.ImageField(null=True, upload_to=b'std/img/%Y/%m/%d', blank=True)),
                ('std_img02', models.ImageField(null=True, upload_to=b'std/img/%Y/%m/%d', blank=True)),
                ('std_img03', models.ImageField(null=True, upload_to=b'std/img/%Y/%m/%d', blank=True)),
                ('std_img04', models.ImageField(null=True, upload_to=b'std/img/%Y/%m/%d', blank=True)),
                ('std_img05', models.ImageField(null=True, upload_to=b'std/img/%Y/%m/%d', blank=True)),
                ('std_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSptLinux',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('stl_title', models.CharField(max_length=255)),
                ('stl_name', models.CharField(max_length=128)),
                ('stl_pw', models.CharField(max_length=128)),
                ('stl_contents', models.TextField()),
                ('stl_author', models.CharField(max_length=128)),
                ('stl_created', models.DateTimeField(auto_now_add=True)),
                ('stl_modified', models.DateTimeField(auto_now=True)),
                ('stl_file01', models.FileField(null=True, upload_to=b'stl/file/%Y/%m/%d', blank=True)),
                ('stl_file02', models.FileField(null=True, upload_to=b'stl/file/%Y/%m/%d', blank=True)),
                ('stl_file03', models.FileField(null=True, upload_to=b'stl/file/%Y/%m/%d', blank=True)),
                ('stl_file04', models.FileField(null=True, upload_to=b'stl/file/%Y/%m/%d', blank=True)),
                ('stl_file05', models.FileField(null=True, upload_to=b'stl/file/%Y/%m/%d', blank=True)),
                ('stl_img01', models.ImageField(null=True, upload_to=b'stl/img/%Y/%m/%d', blank=True)),
                ('stl_img02', models.ImageField(null=True, upload_to=b'stl/img/%Y/%m/%d', blank=True)),
                ('stl_img03', models.ImageField(null=True, upload_to=b'stl/img/%Y/%m/%d', blank=True)),
                ('stl_img04', models.ImageField(null=True, upload_to=b'stl/img/%Y/%m/%d', blank=True)),
                ('stl_img05', models.ImageField(null=True, upload_to=b'stl/img/%Y/%m/%d', blank=True)),
                ('stl_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSptServer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('stv_title', models.CharField(max_length=255)),
                ('stv_name', models.CharField(max_length=128)),
                ('stv_pw', models.CharField(max_length=128)),
                ('stv_contents', models.TextField()),
                ('stv_author', models.CharField(max_length=128)),
                ('stv_created', models.DateTimeField(auto_now_add=True)),
                ('stv_modified', models.DateTimeField(auto_now=True)),
                ('stv_file01', models.FileField(null=True, upload_to=b'stv/file/%Y/%m/%d', blank=True)),
                ('stv_file02', models.FileField(null=True, upload_to=b'stv/file/%Y/%m/%d', blank=True)),
                ('stv_file03', models.FileField(null=True, upload_to=b'stv/file/%Y/%m/%d', blank=True)),
                ('stv_file04', models.FileField(null=True, upload_to=b'stv/file/%Y/%m/%d', blank=True)),
                ('stv_file05', models.FileField(null=True, upload_to=b'stv/file/%Y/%m/%d', blank=True)),
                ('stv_img01', models.ImageField(null=True, upload_to=b'stv/img/%Y/%m/%d', blank=True)),
                ('stv_img02', models.ImageField(null=True, upload_to=b'stv/img/%Y/%m/%d', blank=True)),
                ('stv_img03', models.ImageField(null=True, upload_to=b'stv/img/%Y/%m/%d', blank=True)),
                ('stv_img04', models.ImageField(null=True, upload_to=b'stv/img/%Y/%m/%d', blank=True)),
                ('stv_img05', models.ImageField(null=True, upload_to=b'stv/img/%Y/%m/%d', blank=True)),
                ('stv_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSptStorage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('stt_title', models.CharField(max_length=255)),
                ('stt_name', models.CharField(max_length=128)),
                ('stt_pw', models.CharField(max_length=128)),
                ('stt_contents', models.TextField()),
                ('stt_author', models.CharField(max_length=128)),
                ('stt_created', models.DateTimeField(auto_now_add=True)),
                ('stt_modified', models.DateTimeField(auto_now=True)),
                ('stt_file01', models.FileField(null=True, upload_to=b'stt/file/%Y/%m/%d', blank=True)),
                ('stt_file02', models.FileField(null=True, upload_to=b'stt/file/%Y/%m/%d', blank=True)),
                ('stt_file03', models.FileField(null=True, upload_to=b'stt/file/%Y/%m/%d', blank=True)),
                ('stt_file04', models.FileField(null=True, upload_to=b'stt/file/%Y/%m/%d', blank=True)),
                ('stt_file05', models.FileField(null=True, upload_to=b'stt/file/%Y/%m/%d', blank=True)),
                ('stt_img01', models.ImageField(null=True, upload_to=b'stt/img/%Y/%m/%d', blank=True)),
                ('stt_img02', models.ImageField(null=True, upload_to=b'stt/img/%Y/%m/%d', blank=True)),
                ('stt_img03', models.ImageField(null=True, upload_to=b'stt/img/%Y/%m/%d', blank=True)),
                ('stt_img04', models.ImageField(null=True, upload_to=b'stt/img/%Y/%m/%d', blank=True)),
                ('stt_img05', models.ImageField(null=True, upload_to=b'stt/img/%Y/%m/%d', blank=True)),
                ('stt_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSptSwitch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('stc_title', models.CharField(max_length=255)),
                ('stc_name', models.CharField(max_length=128)),
                ('stc_pw', models.CharField(max_length=128)),
                ('stc_contents', models.TextField()),
                ('stc_author', models.CharField(max_length=128)),
                ('stc_created', models.DateTimeField(auto_now_add=True)),
                ('stc_modified', models.DateTimeField(auto_now=True)),
                ('stc_file01', models.FileField(null=True, upload_to=b'stc/file/%Y/%m/%d', blank=True)),
                ('stc_file02', models.FileField(null=True, upload_to=b'stc/file/%Y/%m/%d', blank=True)),
                ('stc_file03', models.FileField(null=True, upload_to=b'stc/file/%Y/%m/%d', blank=True)),
                ('stc_file04', models.FileField(null=True, upload_to=b'stc/file/%Y/%m/%d', blank=True)),
                ('stc_file05', models.FileField(null=True, upload_to=b'stc/file/%Y/%m/%d', blank=True)),
                ('stc_img01', models.ImageField(null=True, upload_to=b'stc/img/%Y/%m/%d', blank=True)),
                ('stc_img02', models.ImageField(null=True, upload_to=b'stc/img/%Y/%m/%d', blank=True)),
                ('stc_img03', models.ImageField(null=True, upload_to=b'stc/img/%Y/%m/%d', blank=True)),
                ('stc_img04', models.ImageField(null=True, upload_to=b'stc/img/%Y/%m/%d', blank=True)),
                ('stc_img05', models.ImageField(null=True, upload_to=b'stc/img/%Y/%m/%d', blank=True)),
                ('stc_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaSptWindows',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('stw_title', models.CharField(max_length=255)),
                ('stw_name', models.CharField(max_length=128)),
                ('stw_pw', models.CharField(max_length=128)),
                ('stw_contents', models.TextField()),
                ('stw_author', models.CharField(max_length=128)),
                ('stw_created', models.DateTimeField(auto_now_add=True)),
                ('stw_modified', models.DateTimeField(auto_now=True)),
                ('stw_file01', models.FileField(null=True, upload_to=b'stw/file/%Y/%m/%d', blank=True)),
                ('stw_file02', models.FileField(null=True, upload_to=b'stw/file/%Y/%m/%d', blank=True)),
                ('stw_file03', models.FileField(null=True, upload_to=b'stw/file/%Y/%m/%d', blank=True)),
                ('stw_file04', models.FileField(null=True, upload_to=b'stw/file/%Y/%m/%d', blank=True)),
                ('stw_file05', models.FileField(null=True, upload_to=b'stw/file/%Y/%m/%d', blank=True)),
                ('stw_img01', models.ImageField(null=True, upload_to=b'stw/img/%Y/%m/%d', blank=True)),
                ('stw_img02', models.ImageField(null=True, upload_to=b'stw/img/%Y/%m/%d', blank=True)),
                ('stw_img03', models.ImageField(null=True, upload_to=b'stw/img/%Y/%m/%d', blank=True)),
                ('stw_img04', models.ImageField(null=True, upload_to=b'stw/img/%Y/%m/%d', blank=True)),
                ('stw_img05', models.ImageField(null=True, upload_to=b'stw/img/%Y/%m/%d', blank=True)),
                ('stw_comments', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GayaStcComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_stc', models.ForeignKey(to='erp.GayaSptSwitch')),
            ],
        ),
        migrations.CreateModel(
            name='GayaStdComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_std', models.ForeignKey(to='erp.GayaSptDev')),
            ],
        ),
        migrations.CreateModel(
            name='GayaStlComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_stl', models.ForeignKey(to='erp.GayaSptLinux')),
            ],
        ),
        migrations.CreateModel(
            name='GayaSttComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_stt', models.ForeignKey(to='erp.GayaSptStorage')),
            ],
        ),
        migrations.CreateModel(
            name='GayaStvComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_stv', models.ForeignKey(to='erp.GayaSptServer')),
            ],
        ),
        migrations.CreateModel(
            name='GayaStwComments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('com_name', models.CharField(max_length=64)),
                ('com_pw', models.CharField(max_length=64)),
                ('com_contents', models.TextField(max_length=2048)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_stw', models.ForeignKey(to='erp.GayaSptWindows')),
            ],
        ),
        migrations.CreateModel(
            name='HA201_TP',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pro_name', models.CharField(max_length=128)),
                ('pro_class', models.CharField(max_length=128)),
                ('pro_pn', models.CharField(max_length=128)),
                ('pro_sn', models.CharField(unique=True, max_length=128)),
                ('pro_state', models.IntegerField(default=0, null=True, blank=True)),
                ('pro_using', models.IntegerField(default=0, null=True, blank=True)),
                ('pro_out', models.IntegerField(default=0, null=True, blank=True)),
                ('pro_author', models.CharField(max_length=128)),
                ('pro_created', models.DateTimeField(auto_now_add=True)),
                ('pro_modified', models.DateTimeField(auto_now=True)),
                ('pro_note', models.TextField(null=True, blank=True)),
                ('pro_comments', models.PositiveSmallIntegerField(default=0, null=True)),
                ('pro_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('isr_completeday', models.DateField(null=True, blank=True)),
                ('isr_complete', models.IntegerField(default=0, null=True, blank=True)),
                ('isr_add', models.IntegerField(default=0, null=True, blank=True)),
                ('isr_report', models.FileField(null=True, upload_to=b'isr/file/%Y/%m/%d', blank=True)),
                ('isr_out', models.IntegerField(default=0, null=True, blank=True)),
                ('isr_author', models.CharField(max_length=128)),
                ('isr_created', models.DateTimeField(auto_now_add=True)),
                ('isr_modified', models.DateTimeField(auto_now=True)),
                ('isr_note', models.TextField(null=True, blank=True)),
                ('isr_asr', models.ForeignKey(to='erp.AssembleReport')),
                ('isr_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('orr_complete', models.IntegerField(default=0, null=True, blank=True)),
                ('orr_add', models.IntegerField(default=0, null=True, blank=True)),
                ('orr_author', models.CharField(max_length=128)),
                ('orr_created', models.DateTimeField(auto_now_add=True)),
                ('orr_modified', models.DateTimeField(auto_now=True)),
                ('orr_note', models.TextField(null=True, blank=True)),
                ('orr_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('orr_ord', models.ForeignKey(to='erp.GayaOrder')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pcr_completeday', models.DateField(null=True, blank=True)),
                ('pcr_complete', models.IntegerField(default=0, null=True, blank=True)),
                ('pcr_add', models.IntegerField(default=0, null=True, blank=True)),
                ('pcr_report', models.FileField(null=True, upload_to=b'pcr/file/%Y/%m/%d', blank=True)),
                ('pcr_out', models.IntegerField(default=0, null=True, blank=True)),
                ('pcr_author', models.CharField(max_length=128)),
                ('pcr_created', models.DateTimeField(auto_now_add=True)),
                ('pcr_modified', models.DateTimeField(auto_now=True)),
                ('pcr_note', models.TextField(null=True, blank=True)),
                ('pcr_emp', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('pcr_isr', models.ForeignKey(to='erp.InspectionReport')),
            ],
        ),
        migrations.AddField(
            model_name='orderreport',
            name='orr_pcr',
            field=models.ForeignKey(to='erp.PackagingReport'),
        ),
        migrations.AddField(
            model_name='gayascfcomments',
            name='com_scf',
            field=models.ForeignKey(to='erp.GayaSclFree'),
        ),
        migrations.AddField(
            model_name='gayascccomments',
            name='com_scc',
            field=models.ForeignKey(to='erp.GayaSclCommon'),
        ),
        migrations.AddField(
            model_name='gayaorder',
            name='ord_pro',
            field=models.ForeignKey(to='erp.GayaProductInfo'),
        ),
        migrations.AddField(
            model_name='gayaordcomments',
            name='com_ord',
            field=models.ForeignKey(to='erp.GayaOrder'),
        ),
        migrations.AddField(
            model_name='gayacuscomments',
            name='com_cus',
            field=models.ForeignKey(to='erp.GayaCustomer'),
        ),
        migrations.AddField(
            model_name='gaya_ha201tp_comments',
            name='com_ha201tp',
            field=models.ForeignKey(to='erp.HA201_TP'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='dlr_orr',
            field=models.ForeignKey(to='erp.OrderReport'),
        ),
    ]
